# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tela_jogar_online.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Jogar_Online(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(220, 138, 221);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.entrarFila = QtWidgets.QPushButton(self.centralwidget)
        self.entrarFila.setGeometry(QtCore.QRect(120, 280, 161, 31))
        self.entrarFila.setObjectName("entrarFila")
        self.procurarPartid = QtWidgets.QPushButton(self.centralwidget)
        self.procurarPartid.setGeometry(QtCore.QRect(560, 280, 161, 31))
        self.procurarPartid.setObjectName("procurarPartid")
        self.botaoVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoVoltar.setGeometry(QtCore.QRect(670, 490, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        self.botaoVoltar.setFont(font)
        self.botaoVoltar.setObjectName("botaoVoltar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.entrarFila.setText(_translate("MainWindow", "ENTRAR NA FILA"))
        self.procurarPartid.setText(_translate("MainWindow", "PROCURAR PARTIDA"))
        self.botaoVoltar.setText(_translate("MainWindow", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Jogar_Online()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
